language: node_js
sudo: false
node_js:
- 10
- 8
- 6
- 4
install:
- npm install
script:
- npm run clean
- npm run build
- npm run lint
deploy:
  provider: npm
  email: services@serverless.com
  skip_cleanup: true
  on:
    branch: master
    tags: true
    repo: serverless/platform-sdk
  api_key:
    secure: esuYUP818rgORAQFGsN9kbhd+YkRdBEhK5vspLJH2z6Vl6iBPASFcGlFBs+whv8OfqwoO1CYyAkzlhQJdTTKf7rKmoEu8+yBEzFVkuSqxZ3sNISKmDiyitro1cmz1T47rrkjRn83hMwybLayVWMD6hc8mQ6qoM23zy1tbYf4GTSNmLHPTgg7szSclfIcNFA/hpSQR5l1tCgTF6MYqeHcsG5ofMi6Q83RDbfYLXdNOh4XkgAi8hvRCYyb5PHbFaWuwSf9BG4MifBtKdr5peijsKaFcSPoRprXWhhUEN9IPqMrp/SPUYVgB0JNLDdAAMvPqSb/7V6gA2cYGDi+XiEuJxhW+dw4K2Vkusnz0NlCUVeJVR0gO1tRECbFOEn4wn3grNncpk+PSXrb2ttDRaRE3+jfw5JMj60AvV1aynYEiizzKUy6y+UwilnwugiuKDMBrQu3wcKZCdoOhChHKOfOolEXvD3D+TePWsujW3ZO0GUcgp62qDtNcySHuALhFTCr4/pCtlJb5iEaR/EOKRPbTuZi9E+/Q2221bidSyvxj3aUvm/Bzu/EQdQtnuOTP0U02k8DF08M4YyCvpNp9xbcaHz2MbJvFt/OoAecItsq9AZmDzNvV25UcMs+OQ9w5eNoEjoWkx7G/T8XpCbvp5EnSrgatQTu5ilGI3+ebzboThM=
